language: generic

services:
  - docker

before_script:
  - docker build -t trntv/php-async:latest -f .ci/docker/Dockerfile .ci/docker/

script:
  - composer install --ignore-platform-reqs
  - export DIR=$(pwd)
  - docker run -v ${DIR}/:/app trntv/php-async vendor/bin/phpunit -c phpunit.xml.dist

deploy:
  provider: script
  script: bash .ci/travis/deploy.sh
  on:
    branch: master
